#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pothole.create:
  path: /potholes
  controller: App\Controller\PotholeController::upload
  methods: POST

pothole.list:
  path: /potholes
  controller: App\Controller\PotholeController::all
  methods: GET